accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [path("signup/", views.SignupView, name="signup"),
               path("login/", views.LoginView.as_view(), name="login"),
               path("logout/", views.log_out, name="logout")]

config/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("api/v1/posts/",include("posts.api.urls",namespace ="api_posts")),
    path("api/v1/accounts/",include("accounts.api.urls",namespace="api_accounts")),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.home, name="home"),
    path("QnA/", views.CreateQnAView.as_view(), name="QnA"),
    path("<int:pk>/", views.QnA_detail.as_view(), name="QnA_detail"),
    path("<int:qna_pk>/comment/", views.Comment, name="comment"),
    path("<int:qna_pk>/edit/", views.QnAUpdateView.as_view(), name="QnA_edit"),
    path("<int:qna_pk>/delete/", views.QnA_delete, name="QnA_delete"),
    path(
        "<int:qna_pk>/comment/<int:comment_pk>/delete/",
        views.Comment_Delete.as_view(),
        name="comment_delete",
    ),
    path(
        "<int:qna_pk>/comment/<int:comment_pk>/edit/",
        views.Comment_edit,
        name="comment_edit",
    ),
    path(
        "<int:qna_pk>/comment/<int:comment_pk>/update/",
        views.Comment_update,
        name="comment_update",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static 'tailwind.output.css' %}'>
    <link rel="stylesheet" href='{% static 'common.css' %}'>
    <title>liongram</title>
</head>
<body class = "t-text-gray-900 t-mt-24 t-font-light">
    <header class = "t-container t-max-w-full t-inset-0 t-flex t-items-center t-justify-between t-px-3 t-h-20 t-border-b t-border-gray-500 t-fixed t-bg-white">
        <a href="{% url 'posts:home' %}" class="t-text-xl t-pl-3 ">
            <span class = "t-text-red-600">Liongram</span>
        </a>
        <ul class = "t-flex t-items-center t-text-sm t-font-bold t-h-full">
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}" class="t-ml-8 t-border-b-2 t-border-white t-h-full t-flex t-items-center">로그아웃</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}" class="t-ml-8 t-border-b-2 t-border-white t-h-full t-flex t-items-center">로그인</a></li>
                <li><a href="{% url 'accounts:signup' %}" class="t-ml-8 t-border-b-2 t-border-white t-h-full t-flex t-items-center">회원가입</a></li>
            {% endif %}
                
        </ul>
    </header>
    
    {% block content %}
    {% endblock content %}
        
</body>
</html> 

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table class="t-flex t-flex-col t-pl-10">
        <thead>
            <tr> 
                <th>제목</th>
                <th>조회수</th>
                <th>댓글수</th>
                <th>작성일자</th>
            </tr>     
        </thead>
        <tbody class="t-mt-10 t-justify-between">
            {% for QnA in QnA_list %}
            <tr class="t-flex">
                <td>
                    <a href="{% url 'posts:QnA_detail' QnA.pk %}">
                        <span>{{QnA.title }}</span>
                    </a>
                </td>
                <td>0</td>
                <td>{{QnA.Comment.count}}</td>
                <td>{{QnA.updated}}</td>
                    
                {% endfor %}
            </tr>
         </tbody>
    </table>
    <div class="t-m-10 t-rounded-sm t-py-5 t-text-lg t-font-bold t-w-full">
        <a href="{% url 'posts:QnA' %}">문의하기</a>
    </div>    

{% endblock content %}